name: Unitests
on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    environment: staging variables
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Verify environment variables (safely)
      run: |
        echo "Listing environment variable names (values hidden for security):"
        env | cut -d= -f1 | sort
        echo "Number of environment variables:"
        env | wc -l
    
    - name: Test with pytest
      env: ${{ secrets }}
      run: |
        cd app
        pytest -v
